### ISSUE TITLE
"request PO term" button still points to Sourceforge

### ISSUE THREAD

**Issue by austinmeier** [Planteome/planteome-core#10]
Like the title says:  
http://www.plantontology.org/amigo/go.cgi?search_constraint=terms&action=replace_tree

The request button should point to the issues page on the PO repository on GitHub:

https://github.com/Planteome/plant-ontology/issues

**Comment by cmungall** [comment]
I recommend switching to AmiGO 2

**Comment by elserj** [comment]
Done on all sites for PO.
