### ISSUE TITLE
"Help" button on PO browser is pointing to a page that doesn't exist.

### ISSUE THREAD

**Issue by austinmeier** [Planteome/planteome-core#11]
I'm not sure if there should be a help page on the Plantontology.org page, or if this should redirect users to the wiki...  

http://www.plantontology.org/amigo/go.cgi?search_constraint=terms&action=replace_tree

**Comment by elserj** [comment]
Was working on beta since it was never updated to drupal.  Fixed with an Alias in httpd.conf for "amigo_user_guide" on dev, live, and iPlant.

Alias /amigo_user_guide/ "/data/www/plantontology/po_amigo/docs/amigo/docs/user_guide/"
