### ISSUE TITLE
Replace GO logo with Planteome

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#12]
This is a good place to start on the theming.  I have it in various formats.

**Comment by elserj** [comment]
I managed to create a transparent version that looks a bit better, but it may have too much text on it.  Can you take a look and let me know what you think?  http://dev.planteome.org

**Comment by cooperl09** [comment]
Agreed, I think the print is too small.

**Comment by elserj** [comment]
I managed to figure out how to change the size, it was relatively easy.  Closing for now. 
Planteome/amigo@e2eefe78f1ad5939488eae8276d4358b5bd1
Planteome/amigo@fd774b2
