### ISSUE TITLE
Links to GitHub Issue trackers are not working 

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#15]
Links to GitHub Issue trackers (ie PO_GIT; TO_GIT; EO_GIT; PSO_GIT)  are not working.  They show up in the "mappings" tab.

**Comment by cmungall** [comment]
I recommend using the URLs directly

**Comment by cooperl09** [comment]
Could you please explain what you mean by this.

**Comment by cmungall** [comment]
e.g.

```
xref: https://github.com/Planteome/planteome-ontology-browsers/issues/15
```

**Comment by cooperl09** [comment]
This issue was moved to Planteome/amigo#24
