### ISSUE TITLE
change colors

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#16]
.....

**Comment by elserj** [comment]
Any recommendations on what colors to switch it to?  I have figured out exactly how to do this, but unsure what to change to, could use some advice.  I'm not real good with picking colors for the UI.  Do we want to use similar orange colors as we did on the current planteome.org site?
Maybe @preecej and @jaiswalp have input here?

**Comment by cooperl09** [comment]
Can you give us a couple options to choose from.  Maybe change it and take a screenshot to compare them?  Personally I am not crazy about the orange/brown scheme, prefer greens.

**Comment by jaiswalp** [comment]
On 12/4/2015 2:42 PM, elserj wrote:

> Do we want to use similar orange colors as we did on the current
> planteome.org site?

yes. if possible

## 

Pankaj Jaiswal, PhD
Associate Professor
Dept. of Botany and Plant Pathology
2082 Cordley Hall
Oregon State University
Corvallis, OR, 97331
USA

Ph.: +1-541-737-8471
Fax: +1-541-737-3573
email: jaiswalp@oregonstate.edu
Web: http://jaiswallab.cgrb.oregonstate.edu/

**Comment by elserj** [comment]
I think I got all of these done in Planteome/amigo@36e8d1af37a4f37d293419930436c58c8de829d9
