### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by cmungall** [Planteome/planteome-core#18]
There seems to have been some confusion with this repo

It was originally created to satisfy this request
https://github.com/Planteome/plant-trait-ontology/issues/2

We need a planteome.owl importer for the whole project

This repo was originally called planteome-amigo2, and we placed the planteome.owl file in here

It was then renamed to planteome-ontology-browsers, but the importer file doesn't belong in this repo

**Comment by cooperl09** [comment]
Renamed planteome-core to avoid confusion. Closing
Users will need to drop and re-add the remote on your local copy
