### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by cmungall** [Planteome/planteome-core#2]
The use of planteome.owl extends beyond just amigo2, and will be used throughout the project

I suggest `planteome-root` but I appreciate `root` is not a good CS term when dealing with plants

Another possibility is just `planteome-ontology`

**Comment by cooperl09** [comment]
I think planteome-ontology would be confusing as there is no ontology files there.  I think Amigo2 seems fine for now, we can always change it later, if the need arises.  What other uses does the planteome.owl have?

**Comment by cmungall** [comment]
Everything. We'll need to move away from the view of multiple silo ontologies weakly connected with xrefs to a single coherent ontology connected via owl axioms, where what were previously considered standalone ontologies become modules.

In terms of actual practical uses, things like a CI job that checks the suite for coherency. As everyone becomes more comfortable with OWL and Protege this will all make more sense

**Comment by cooperl09** [comment]
Renamed "planteome-ontology-browsers" as we need some place to store code and discuss issues with all the various browsers we are dealing with. Will make specific labels for them.
