### ISSUE TITLE
Relations are not being recognized and displayed in AmiGO 2.0

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#20]
Currently, there are a limited number of relations being recognized by AmiGO 2.0:
is_a
part_of
occurs_in
In the Plant Ontology file, we have a number of important relations that are missing in the browser view:

Relations with examples: 

[Typedef]
id: adjacent_to
name: adjacent_to
xref: RO:0002220

e.g. _id: PO:0025382! 
name: substomatal cavity
relationship: adjacent_to PO:0008032 ! stomatal pore_

[Typedef]
id: derives_by_manipulation_from
name: derives_by_manipulation_from

e.g. 
_id: PO:0000007 leaf-derived cultured plant cell 
relationship: derives_by_manipulation_from PO:0025034 ! leaf_

[Typedef]
id: develops_from
name: develops_from
xref: RO:0002202
is_transitive: true

e.g.
_id: PO:0000015
name: cotyledon primordium
relationship: develops_from PO:0025432 ! cotyledon anlagen_

[Typedef]
id: has_part
name: has_part
xref: BFO:0000051
is_transitive: true

e.g. 
_id: PO:0009049 
name: inflorescence
relationship: has_part PO:0009046 ! flower_

[Typedef]
id: has_participant
name: has_participant
xref: BFO:0000057

e.g. 
_id: PO:0007033 
name: whole plant development stage
relationship: has_participant PO:0000003 ! whole plant_

[Typedef]
id: located_in
name: located_in
xref: RO:0001025

e.g.
_id: PO:0025281 
name: pollen; 
relationship: located_in PO:0025277 ! pollen sac_

[Typedef]
id: participates_in
name: participates_in
xref: BFO:0000056

e.g.
_id: PO:0000423
name: plant zygote
relationship: participates_in PO:0001097 ! plant zygote stage_

[Typedef]
id: preceded_by
name: preceded_by
xref: BFO:0000062
is_transitive: true

e.g.
_id: PO:0001040
name: dry seed stage
relationship: preceded_by PO:0007632 ! seed maturation stage_

[Typedef]
id: precedes
name: precedes
xref: BFO:0000063

e.g.
_id: PO:0001078
name: plant embryo cotyledonary stage
relationship: preceded_by PO:0004507 ! plant embryo bilateral stage
relationship: precedes PO:0001081 ! mature plant embryo stage_

**Comment by cmungall** [comment]
@kltm @hditeze I can't find the ticket on the main tracker right now but I know we've discussed this a few times. We only want to filter relationships for _ancestry_. For direct relationships it's very useful to see and traverse over any relationship types. We really need this in the main amigo. I think this should be relatively straightforward to handle on the owltools end with no changes required on the amigo app or configurations itself

**Comment by cmungall** [comment]
Here: https://github.com/geneontology/amigo/issues/220

**Comment by marieALaporte** [comment]
The CO properties method_of, scale_of and variable_of don't show up neither on the browser.

**Comment by cmungall** [comment]
This is already covered in the main amigo ticket, but if we want a test case that is plant specific, see how anther looks in OLS:

http://www.ebi.ac.uk/ols/beta/ontologies/po/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPO_0009066

I think this gets it right (never mind details about whether a denormalized tree view is the best way of showing things, or if the 'visualize' link gives you a headache). The crucial points are:
- Some kind of relationship lineage display that operates over a subset of the relations (for OLS, isa and part-of; we can include develops-from for amigo if we like)
  - Display of direct incoming and outgoing edges, unrestricted by relationship type

The details of how this would look in amigo would be different. We may have the inferredtreeview as default for the lineage, and we may show what OLS calls 'class relations' in the TermInfo panel, or a new tab. But the information would be the same.

**Comment by cooperl09** [comment]
This issue was moved to Planteome/amigo#20

**Comment by cooperl09** [comment]
This issue was moved to Planteome/amigo#21
