### ISSUE TITLE
links to wikipedia are not working

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/planteome-core#21]
The links to Wikipedia are not working. See the following examples: 
- Incorrect links in PATO:

http://browser.planteome.org/amigo/term/PATO:0001352
http://browser.planteome.org/amigo/term/PATO:0001351
- Not recognised as links in TO:

http://browser.planteome.org/amigo/term/TO:0012001
http://browser.planteome.org/amigo/term/TO:0000523

**Comment by austinmeier** [comment]
The wikipedia stanza in the DBXrefs.yaml looks like this:
- database: Wikipedia
  name: Wikipedia
  generic_urls:
  - http://en.wikipedia.org/
    entity_types:
  - type_name: entity
    type_id: BET:0000000
    url_syntax: http://en.wikipedia.org/wiki/[example_id]
    example_id: Wikipedia:Endoplasmic_reticulum
    example_url: http://en.wikipedia.org/wiki/Endoplasmic_reticulum

So this could be changed on the PATO side by removing the "wikipedia:", and just leaving the URL, or by removing the whole URL and making it conform to the format specified:  "wikipedia: Linear_density"

**Comment by elserj** [comment]
The problem is with the xrefs as they are written in the ontology files.  The dbxref is the correct syntax as pointed out by @austinmeier.  

The 2 links pointed out in the TO seem to be the only references to wikipedia in the file, so those are trivial to fix.  There appear to be 132 in PATO, although some of those seem to be correct, some are image links, but there are a couple as "Wikipedia:Wikipedia" which makes no sense.  Some are actually links to "wiktionary".

It looks like @cmungall is the author for the PATO ontology.  I can probably fix the files and submit a PR, but want to confirm that using the dbxref rather than the full URL is the correct solution.

**Comment by cooperl09** [comment]
fixed the Dbxref to Wikipedia on the following terms:
 [Term]
 id: TO:0000522
 name: stomatal conductance
+def: "It is a numerical measure of the maximum rate of passage of either water vapour or carbon dioxide through the stomata." [GR:pj, Wikipedia:Stomatal_conductance]

 [Term]
 id: TO:0000523
 name: stomatal resistance
+def: "Stomatal resistance (or its inverse, stomatal conductance) can therefore be calculated from the transpiration rate and humidity gradient. (The humidity gradient is the humidity inside the leaf, determined from leaf temperature based on the assumption that the leaf's air spaces are saturated with vapor, minus the humidity of the ambient air, which is measured directly)." [Wikipedia:Stomatal_conductance]
 [Term]
 id: TO:0012001
 name: leaf area index
+def: "Leaf Area Index (LAI) is the ratio of total upper leaf surface of vegetation divided by the surface area of the land on which the vegetation grows." [wikipedia:Leaf_area_index]

**Comment by cmungall** [comment]
On 8 Feb 2016, at 12:42, Austin Meier wrote:

> The wikipedia stanza in the DBXrefs.yaml looks like this:
> - database: Wikipedia
>   name: Wikipedia
>   generic_urls:
>   - http://en.wikipedia.org/
>     entity_types:
>   - type_name: entity
>     type_id: BET:0000000
>     url_syntax: http://en.wikipedia.org/wiki/[example_id]
>     example_id: Wikipedia:Endoplasmic_reticulum
>     example_url: http://en.wikipedia.org/wiki/Endoplasmic_reticulum
> 
> So this could be changed on the PATO side by removing the 
> "wikipedia:", and just leaving the URL, or by removing the whole URL 
> and making it conform to the format specified:  "wikipedia: 
> Linear_density"

Yes Wikipedia:Linear_density

We do it in this way in uberon, but we pre-expand to complete URLs for 
the OWL edition. This will be the more common pattern in future

**Comment by cooperl09** [comment]
This issue was moved to Planteome/amigo#22
