### ISSUE TITLE
Display in Protégé

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/planteome-core#26]
Do we need to import the whole PATO ontology into the planteome.owl file? 
I am asking that as it seems that PATO is messing up the display in Protégé of the classes occurrent and continuant (maybe others), because there are obsolete classes in PATO with the same labels. 
Not a big deal, but that would be nice to have a clean display of the planteome.owl file in Protégé.

**Comment by cmungall** [comment]
Can you make a ticket on the pato tracker to prefix all obsolete term
labels?

**Comment by marieALaporte** [comment]
fixed in https://github.com/pato-ontology/pato/issues/116
