### ISSUE TITLE
 Cannot search for EO or PDO terms by ID # 

### ISSUE THREAD

**Issue by seymourmegan** [Planteome/planteome-core#3]
We are unable to look up EO or PDO terms by ID # in the TO,EO, PSO Dev browser.
http://palea.cgrb.oregonstate.edu/trait_ontology/cgi-bin/trait_amigo/go.cgi

For example:
When I search for PDO:0000176, the dev browser returns nothing.
Sometimes it will find the PDO or EO ID in a definition and return that, but otherwise does not work.
Since this was originally just for the TO, it seems to be set only to find TO ids.

**Comment by cooperl09** [comment]
This issue was moved to Planteome/amigo#25
