### ISSUE TITLE
Links to TAIR genes not working in PO-Live

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#5]
For example the link from this page: 
http://www.plantontology.org/amigo/go.cgi?search_constraint=gp&view=details&session_id=8749b1443639738&gp=locus:2009457

for AT1G22590;  AGAMOUS-like 87
TAIR:locus:2009457
goes to: http://www.arabidopsis.org/servlets/TairObject?type=locus&name=locus:2009457

Returns an error.
Should go to: 
https://www.arabidopsis.org/servlets/TairObject?accession=locus:2009457

I had sent a question to TAIR about the links to the Locus ids earlier this summer, this is the response I got:

---

From TAIR:
The form for making external hyperlinks to TAIR pages is shown on  this page
https://www.arabidopsis.org/about/linktotair.jsp

So for your example:
LTP12- AT3G51590,  locus:2081840.
The form of the hyperlink would be:
https://www.arabidopsis.org/servlets/TairObject?accession=locus:2081840

I tried that and it (and others) from the file and they are linking to the proper pages in TAIR.

If you are just linking to loci you can also use the name as they unique identifier .The base URL for linking is:
https://arabidopsis.org/servlets/TairObject?type=locus&name=

e.g. https://www.arabidopsis.org/servlets/TairObject?type=locus&name=AT3G51590

@elserj and @austinmeier - Could you please check into this and update the dbxrefs?

**Comment by cooperl09** [comment]
From: [Planteome Ontology Browsers Table](https://docs.google.com/spreadsheets/d/1Kht1MmrT8opPSmjamme6alz70JME-Xu8B2vmNE4KmCY/edit?usp=sharing)
" 9-23 JE copied the namemunger from beta to live, so everything should be working. "

Need to check these and verify....

**Comment by elserj** [comment]
Fixed on all sites (Live, dev, beta, and iPlant).  NameMunger.pm needed to be updated.

**Comment by cooperl09** [comment]
Updated on: https://github.com/Planteome/common-files-for-ref-ontologies/blob/master/PO_DBXref.txt?

**Comment by elserj** [comment]
It is now.
