### ISSUE TITLE
Link to git repo from update on browser?

### ISSUE THREAD

**Issue by cooperl09** [Planteome/planteome-core#8]
Is it possible to make the "git Version: 01901fa " a link to the repo?
This would be very useful
![screen shot 2015-10-01 at 10 41 31 am](https://cloud.githubusercontent.com/assets/7378000/10228706/01a975a8-6829-11e5-9838-8112dda1d2de.png)

**Comment by cmungall** [comment]
I recommend going straight to amigo2

**Comment by cooperl09** [comment]
Link to the commit on PO-Dev and PO_beta are working. Will need to check PO-Live once release is out.

**Comment by cooperl09** [comment]
Working on PO_live as well as of release #21.
